### ISSUE TITLE
Add another class

### ISSUE THREAD

**Issue by nution101** [krig/eventcontrol#3]
When I add another class to the ec-dot elements dynamically or via `$.each(self.settings.data, function (i, item) {
            self.items.append('<div class="ec-dot" style="left:0px;top:0px;"></div>');` 

like say : `self.items.append('<div class="ec-dot tooltip" style="left:0px;top:0px;"></div>');`

The dots will break.

**Comment by krig** [comment]
Ah, appending to the items list is not the way to do that, but using jquery to find all the dots and setting the tooltip class that way should work. After creating the eventcontrol, call `$('.ec-dot').addClass('tooltip');`.
I create the items list to have a dot for each data point, so adding to it gets the two lists out of sync..
You can also do it in the oncreate callback, just `item.addClass("tooltip");`. Or in the onhover function, you should be able to do `if (inout == "out") { item.removeClass("tooltip"); } else { item.addClass("tooltip"); }` to have a tooltip on the hovered dot.

**Comment by nution101** [comment]
`item.addClass("tooltip");`  seems to throw an error, but `element.addClass("tooltip");`  works, however the dots do not appear on the chart. Sort of what I was seeing before but I was just trying different ways of injecting the class. If I say, remove that class on hover, the dots reappear, but anytime I add the tooltip class to a dot element, it disappears. If I instepect it in the DOM I can see it adds it properly `<div class="ec-dot tooltip" style="left: 2px; top: 2px; color: rgb(186, 184, 4);"></div>` but doesn't show in the graph visually. 

Also, its not throwing any errors, and I can still hover over a dot (though its invisible), and see other actions taking place, so the whole thing isn't breaking down, its more an issue with loosing the visuals of the dots.

**Comment by krig** [comment]
I see.. Alright, I'll look into it and see if I can figure it out.

**Comment by nution101** [comment]
This was my bad actually. the tooltip class was over riding some css properties of ec-dot to display: none; so they were coming up empty. There is some strange behavior still, but I don't so much accredit that to this control, more so that my app is kind of bloated and complicated at this point. So I need to spend some time cleaning things up a bit.

**Comment by krig** [comment]
Alright, let me know if you find any other issues :)
